[package]
name = "spaceapi"
version = "0.4.0"
documentation = "https://coredump-ch.github.io/rust-docs/spaceapi/spaceapi/index.html"
repository = "https://github.com/coredump-ch/spaceapi-rs/"
license = "MIT OR Apache-2.0"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
    "Stefan Schindler <stefan@estada.ch>",
]
description = "Space API types and serialization/deserialization."
readme = "README.md"
keywords = ["spaceapi", "hackerspaces", "status", "api"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
    "AUTHORS.md",
]
build="build.rs"

[build-dependencies]
serde_codegen = "^0.8"

[dependencies]
log = "^0.3"
serde = "^0.8"
serde_json = "^0.8"
